[package]
name = "zinnia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.3"
rustpotter = "3.0.2"
tray-item = { version = "0.10.0", features = ["ksni"] }
png = "0.16"
vosk = "0.3.1"
